# Generated by Django 5.2.3 on 2025-09-05 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=150, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("page", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[("click", "Click"), ("input", "Input")], max_length=10
                    ),
                ),
                ("element", models.TextField()),
                ("value", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp", "-id"),
            },
        ),
    ]
